---
- hosts: app
  become: yes
  tasks:
    - name: ensure latest nginx version is installed
      apt: name=nginx state=latest
    - name: start nginx
      service:
         name: nginx
         state: started
    - name : inject index.html of our choice
      copy:
         src: index.html
         dest: /var/www/html/index.html
    - name: restart nginx
      service:
        name: nginx
        state: restarted
